apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-repo-conjur-sync
spec:
  refreshInterval: 55s
  secretStoreRef:
    name: conjur
    kind: SecretStore
  target:
    name: gitlab-repo-creds-conjur
    template:
      metadata:
        labels:
          # This label tells ArgoCD to treat this secret as a repository config
          argocd.argoproj.io/secret-type: repository
      data:
        name: "GitLab-Conjur-Repo"
        type: git
        url: "{GITLAB_REPO_URL}"
        project: "{APP_NAMESPACE}"
        forceHttpBasicAuth: "true"
        insecure: "true"
        # Mapping Conjur internal keys to ArgoCD expected fields
        username: "{{ .user }}"
        password: "{{ .pass }}"
  data:
    - secretKey: user
      remoteRef:
        key: "{PATH_USER}"
    - secretKey: pass
      remoteRef:
        key: "{PATH_TOKEN}"