---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-eso
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: conjur
spec:
  provider:
    conjur:
      url: {CONJUR_URL}
      caProvider:
        type: ConfigMap
        name: conjur-cm
        key: CONJUR_SSL_CERTIFICATE
      auth:
        jwt:
          account: {CONJUR_ACCOUNT}
          serviceID: k8s
          serviceAccountRef:
            name: k8s-eso
            audiences:
              - cybrdemo